accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login$', 'accounts.views.persona_login', name='persona_login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

lists/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^(\d+)/$', 'lists.views.view_list', name='view_list'),
    url(r'^new$', 'lists.views.new_list', name='new_list'),
    url(r'^users/(.+)/$', 'lists.views.my_lists', name='my_lists'),
    # url(r'^admin/', include(admin.site.urls)),
)

superlists/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^lists/', include('lists.urls')),
    url(r'^accounts/', include('accounts.urls')),
    # url(r'^admin/', include(admin.site.urls)),
)

accounts/models.py
from django.db import models
from django.utils import timezone

class User(models.Model):
    email = models.EmailField(primary_key=True)
    last_login = models.DateTimeField(default=timezone.now)
    REQUIRED_FIELDS = ()
    USERNAME_FIELD = 'email'

    def is_authenticated(self):
        return True

lists/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    @property
    def name(self):
        return self.item_set.first().text

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField()
    list = models.ForeignKey(List)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item, List

DUPLICATE_ITEM_ERROR = "You've already got this in your list"
EMPTY_LIST_ERROR = "You can't have an empty list item"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
            })
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR},
        }


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)


class NewListForm(ItemForm):

    def save(self, owner):
        if owner.is_authenticated():
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

accounts/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse

def persona_login(request):
    user = authenticate(assertion=request.POST['assertion'])
    if user:
        login(request, user)
    return HttpResponse(content='OK')

lists/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.shortcuts import redirect, render
from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from lists.models import Item, List

User = get_user_model()


def home_page(request):
    items = Item.objects.all()
    return render(request, 'home.html', {'form': ItemForm()})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, 'form': form})

def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})

def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

deploy_tools/ansible/roles/app/templates/gunicorn-upstart.conf.j2
description "Gunicorn server for {{ site_fqdn }}"

start on net-device-up
stop on shutdown

respawn

setuid {{ deployment_user }}
chdir /home/{{ deployment_user }}/sites/{{ site_fqdn }}

exec virtualenv/bin/gunicorn \
    --bind unix:/tmp/{{ site_fqdn }}.socket \
    --access-logfile access.log \
    --error-logfile error.log \
    {{ django_project_name }}.wsgi:application

deploy_tools/ansible/roles/app/templates/nginx-site.conf.j2
server {
    listen 80;
    server_name {{ site_fqdn }};

    location /static {
        alias /home/{{ deployment_user }}/sites/{{ site_fqdn }}/static;
    }

    location / {
        proxy_set_header Host $host;
	proxy_pass http://unix:/tmp/{{ site_fqdn }}.socket;
    }
}

deploy_tools/ansible/roles/jenkins/templates/admin_user.xml.j2
<?xml version='1.0' encoding='UTF-8'?>
<user>
  <fullName>Admin User</fullName>
  <properties>
    <hudson.model.PaneStatusProperties>
      <collapsed/>
    </hudson.model.PaneStatusProperties>
    <jenkins.security.ApiTokenProperty>
      <apiToken>{{ jenkins_admin_api_token }}</apiToken>
    </jenkins.security.ApiTokenProperty>
    <com.cloudbees.plugins.credentials.UserCredentialsProvider_-UserCredentialsProperty plugin="credentials@1.9.4">
      <domainCredentialsMap class="hudson.util.CopyOnWriteMap$Hash"/>
    </com.cloudbees.plugins.credentials.UserCredentialsProvider_-UserCredentialsProperty>
    <hudson.model.MyViewsProperty>
      <views>
        <hudson.model.AllView>
          <owner class="hudson.model.MyViewsProperty" reference="../../.."/>
          <name>All</name>
          <filterExecutors>false</filterExecutors>
          <filterQueue>false</filterQueue>
          <properties class="hudson.model.View$PropertyList"/>
        </hudson.model.AllView>
      </views>
    </hudson.model.MyViewsProperty>
    <hudson.search.UserSearchProperty>
      <insensitiveSearch>false</insensitiveSearch>
    </hudson.search.UserSearchProperty>
    <hudson.security.HudsonPrivateSecurityRealm_-Details>
      <passwordHash>{{ jenkins_admin_password_hash }}</passwordHash>
    </hudson.security.HudsonPrivateSecurityRealm_-Details>
    <org.jenkinsci.main.modules.cli.auth.ssh.UserPropertyImpl>
      <authorizedKeys>{{ jenkins_public_key }}</authorizedKeys>
    </org.jenkinsci.main.modules.cli.auth.ssh.UserPropertyImpl>
    <hudson.tasks.Mailer_-UserProperty plugin="mailer@1.8">
        <emailAddress>{{ jenkins_admin_email }}</emailAddress>
    </hudson.tasks.Mailer_-UserProperty>
  </properties>
</user>

deploy_tools/ansible/roles/jenkins/templates/config.xml.j2
<?xml version='1.0' encoding='UTF-8'?>
<hudson>
  <disabledAdministrativeMonitors/>
  <version>1.0</version>
  <numExecutors>2</numExecutors>
  <mode>NORMAL</mode>
  <useSecurity>true</useSecurity>
  <authorizationStrategy class="hudson.security.GlobalMatrixAuthorizationStrategy">
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Create:{{ jenkins_admin_user }}</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Delete:{{ jenkins_admin_user }}</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains:{{ jenkins_admin_user }}</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.Update:{{ jenkins_admin_user }}</permission>
    <permission>com.cloudbees.plugins.credentials.CredentialsProvider.View:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Computer.Build:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Computer.Configure:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Computer.Connect:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Computer.Create:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Computer.Delete:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Computer.Disconnect:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Hudson.Administer:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Hudson.ConfigureUpdateCenter:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Hudson.Read:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Hudson.RunScripts:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Hudson.UploadPlugins:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Item.Build:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Item.Cancel:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Item.Configure:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Item.Create:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Item.Delete:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Item.Discover:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Item.Read:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Item.Workspace:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Run.Delete:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.Run.Update:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.View.Configure:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.View.Create:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.View.Delete:{{ jenkins_admin_user }}</permission>
    <permission>hudson.model.View.Read:{{ jenkins_admin_user }}</permission>
  </authorizationStrategy>
  <securityRealm class="hudson.security.HudsonPrivateSecurityRealm">
    <disableSignup>true</disableSignup>
    <enableCaptcha>false</enableCaptcha>
  </securityRealm>
  <disableRememberMe>false</disableRememberMe>
  <projectNamingStrategy class="jenkins.model.ProjectNamingStrategy$DefaultProjectNamingStrategy"/>
  <workspaceDir>${JENKINS_HOME}/workspace/${ITEM_FULLNAME}</workspaceDir>
  <buildsDir>${ITEM_ROOTDIR}/builds</buildsDir>
  <markupFormatter class="hudson.markup.EscapedMarkupFormatter"/>
  <jdks/>
  <viewsTabBar class="hudson.views.DefaultViewsTabBar"/>
  <myViewsTabBar class="hudson.views.DefaultMyViewsTabBar"/>
  <clouds/>
  <slaves/>
  <scmCheckoutRetryCount>0</scmCheckoutRetryCount>
  <views>
    <hudson.model.AllView>
      <owner class="hudson" reference="../../.."/>
      <name>All</name>
      <filterExecutors>false</filterExecutors>
      <filterQueue>false</filterQueue>
      <properties class="hudson.model.View$PropertyList"/>
    </hudson.model.AllView>
  </views>
  <primaryView>All</primaryView>
  <slaveAgentPort>0</slaveAgentPort>
  <label></label>
  <nodeProperties/>
  <globalNodeProperties/>
</hudson>

deploy_tools/ansible/roles/jenkins/templates/jenkins.j2
# This file was generated by Ansible for {{ansible_fqdn}}
# Do NOT modify this file by hand!
# {{ansible_managed}}

NAME={{jenkins_name}}
JAVA={{jenkins_java}}
JAVA_ARGS="-Djava.awt.headless=true"
PIDFILE={{jenkins_pidfile}}
JENKINS_USER={{jenkins_user}}
JENKINS_GROUP={{jenkins_group}}
JENKINS_WAR={{jenkins_war}}
JENKINS_HOME={{jenkins_home}}
RUN_STANDALONE={{'true' if jenkins_run_standalone else 'false'}}
JENKINS_LOG=/var/log/jenkins/$NAME.log
MAXOPENFILES=8192
HTTP_PORT={{jenkins_http_port}}
PREFIX={{jenkins_prefix}}

# arguments to pass to jenkins.
# --javahome=$JAVA_HOME
# --httpPort=$HTTP_PORT (default 8080; disable with -1)
# --httpsPort=$HTTP_PORT
# --ajp13Port=$AJP_PORT
# --argumentsRealm.passwd.$ADMIN_USER=[password]
# --argumentsRealm.roles.$ADMIN_USER=admin
# --webroot=~/.jenkins/war
# --prefix=$PREFIX
JENKINS_ARGS="--prefix=$PREFIX --webroot=/var/cache/jenkins/war --httpPort=$HTTP_PORT"

deploy_tools/ansible/roles/jenkins/templates/job.xml.j2
<?xml version='1.0' en<?xml version='1.0' encoding='UTF-8'?>
<project>
  <actions/>
  <description></description>
  <keepDependencies>false</keepDependencies>
  <properties/>
  <scm class="hudson.plugins.git.GitSCM" plugin="git@2.2.1">
    <configVersion>2</configVersion>
    <userRemoteConfigs>
      <hudson.plugins.git.UserRemoteConfig>
        <url>{{item.source}}</url>
      </hudson.plugins.git.UserRemoteConfig>
    </userRemoteConfigs>
    <branches>
      <hudson.plugins.git.BranchSpec>
        <name>*/{{item.version|default('master')}}</name>
      </hudson.plugins.git.BranchSpec>
    </branches>
    <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
    <submoduleCfg class="list"/>
    <extensions/>
  </scm>
  <canRoam>true</canRoam>
  <disabled>false</disabled>
  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
  <triggers/>
  <concurrentBuild>false</concurrentBuild>
  <builders>
    <hudson.tasks.Shell>
      <command>{{item.command}}</command>
    </hudson.tasks.Shell>
  </builders>
  <publishers/>
  <buildWrappers/>

deploy_tools/ansible/roles/jenkins/templates/nginx.conf.j2
# This file was generated by Ae for {{ansible_fqdn}}
# Do NOT modify this file by hand!
# {{ansible_managed}}

server {
    listen            80;
    server_name       {{jenkins_nginx_hostname}};
    client_max_body_size 1024m;

    location / {
        proxy_pass http://127.0.0.1:{{jenkins_http_port}};
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
    }

    error_log         {{jenkins_logdir}}/nginx-error.log;
    access_log        {{jenkins_logdir}}/nginx-access.log;

}

deploy_tools/ansible/roles/nginx/templates/nginx.conf.j2
# This file was generated by Ae for {{ ansible_fqdn }}
# Do NOT modify this file by hand!
# {{ansible_managed}}
 
user  {{nginx_user}};
worker_processes  {{nginx_worker_processes}};

events {
    worker_connections  {{nginx_worker_connections}};
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        {{'on' if nginx_sendfile else 'off'}};

    keepalive_timeout  {{nginx_keepalive_timeout}};

    gzip  {{'on' if nginx_gzip else 'off'}};

    server_names_hash_bucket_size {{nginx_server_names_hash_bucket_size}};

    access_log {{nginx_access_log}};
    error_log {{nginx_error_log}};

    {% if nginx_http_options %}{% for name, value in nginx_http_options.items() %}
    {{name}} {{value}};
    {% endfor %}{% endif %}

    {% if nginx_servers %}{% for server in nginx_servers %}
    server {
      {% for option in server %}
      {{option}}
      {% endfor %}
    }
    {% endfor %}{% endif %}

    include {{nginx_dir}}/conf.d/*.conf;
    include {{nginx_dir}}/sites-enabled/*;

}

deploy_tools/ansible/roles/web/templates/nginx.conf.j2
# {{ ansible_managed }}
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# nginx-naxsi config
	##
	# Uncomment it if you installed nginx-naxsi
	##

	#include /etc/nginx/naxsi_core.rules;

	##
	# nginx-passenger config
	##
	# Uncomment it if you installed nginx-passenger
	##
	
	#passenger_root /usr;
	#passenger_ruby /usr/bin/ruby;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>

    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/base.css" rel="stylesheet" media="screen">
</head>
<body>
<div class="container">

    <nav class="navbar navbar-default" role="navigation">
        <a class="navbar-brand" href="/">Superlists</a>
        {% if user.email %}
            <ul class="nav navbar-nav">
                <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
            </ul>
            <a class="btn navbar-btn navbar-right" id="id_logout" href="{% url 'logout' %}">Log out</a>
            <span class="navbar-text navbar-right">Logged in as {{ user.email }}</span>
        {% else %}
            <a class="btn navbar-btn navbar-right" id="id_login" href="#">Sign in</a>
        {% endif %}
    </nav>

    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>

                {% block list_form %}
                <form method="POST" action="{% block form_action %}{% endblock %}" >
                    {{ form.text }}
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="form-group has-error">
                            <span class="help-block">{{ form.text.errors }}</span>
                        </div>
                    {% endif %}
                </form>
                {% endblock %}

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block extra_content %}
            {% endblock %}
        </div>

</div>
<script src="/static/jquery.min.js"></script>
<script src="https://login.persona.org/include.js"></script>
<script src="/static/accounts.js"></script>
<script src="/static/list.js"></script>
<script>
    /*global $, Superlists, navigator */
    $(document).ready(function () {
        var user = "{{ user.email }}" || null;
        var token = "{{ csrf_token }}";
        var urls = {
            login: "{% url 'persona_login' %}",
            // logout: "{% url 'logout' %}",
        };
        Superlists.Accounts.initialize(navigator, user, token, urls);
    });
</script>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}